#/*******************************************************************************
#* Name        : makefile
#* Author      : Nicholas Cali & Kyle Henderson
#* Date        : 6/28/2021
#* Description : build project
#* Pledge      : I pledge my honor that I have abided by the Stevens Honor System.
#******************************************************************************/


all:
	gcc -g -Wall -Werror -pedantic-errors mtsieve.c -o mtsieve -lm -lpthread
clean:
	rm -f mtsieve mtsieve.exe
